TRAIN:
  MAX_ITER: 30000
MODEL:
  PARTIAL_BN: True
  PRETRAINED: True
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-3
LR_SCHEDULER:
  NAME: 'multistep_lr'
  MILESTONES: [ 15000 ]
DATALOADER:
  TRAIN_BATCH_SIZE: 64
  TEST_BATCH_SIZE: 64