NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/tsn_mbv2_ucf101_rgb_raw_dense_1x16x4'
TRAIN:
  MAX_ITER: 30000
  LOG_STEP: 10
  SAVE_STEP: 1000
  EVAL_STEP: 1000
  RESUME: False
  USE_TENSORBOARD: True
DATASETS:
  MODALITY: 'RGB'
  TYPE: 'RawFrame'
  SAMPLE_STRATEGY: 'DenseSample'
  CLIP_LEN: 1
  FRAME_INTERVAL: 16
  NUM_CLIPS: 4
  NUM_SAMPLE_POSITIONS: 1
  TRAIN:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
  TEST:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
TRANSFORM:
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  TRAIN:
    SCALE_JITTER: (256, 320)
    RANDOM_HORIZONTAL_FLIP: True
    COLOR_JITTER: (0.1, 0.1, 0.1, 0.1)
    RANDOM_ROTATION: 10
    RANDOM_CROP: True
    CENTER_CROP: False
    TRAIN_CROP_SIZE: 224
    RANDOM_ERASING: True
  TEST:
    SHORTER_SIDE: 256
    CENTER_CROP: True
    THREE_CROP: False
    TEST_CROP_SIZE: 256
DATALOADER:
  TRAIN_BATCH_SIZE: 96
  TEST_BATCH_SIZE: 96
  NUM_WORKERS: 8
MODEL:
  NAME: 'TSN'
  PRETRAINED: ''
  SYNC_BN: True
  INPUT_SIZE: (224, 224, 3)
  BACKBONE:
    NAME: 'ShuffleNet_v2'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
  HEAD:
    NAME: 'TSNHead'
    FEATURE_DIMS: 1024
    DROPOUT: 0.5
    NUM_CLASSES: 101
  RECOGNIZER:
    NAME: 'TSNRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 1e-2
  WEIGHT_DECAY: 3e-5
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 15000, 25000 ]
  WARMUP:
    ITERATION: 400
    MULTIPLIER: 1.0